# Generated by Django 5.2.17 on 2026-08-27 14:19

from decimal import Decimal
from django.db import migrations, models


def move_product_overrides_to_suppliers(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    Supplier = apps.get_model('suppliers', 'Supplier')
    for product in Product.objects.exclude(supplier_rate_override__isnull=True).order_by('id'):
        Supplier.objects.filter(
            pk=product.supplier_id,
            consignment_rate_override__isnull=True,
        ).update(consignment_rate_override=product.supplier_rate_override)


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('catalog', '0002_product_supplier_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='consignment_rate_override',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.50'), 'Force 50%'), (Decimal('0.30'), 'Force 30%')], decimal_places=2, help_text='Leave blank for automatic campaign calculation. Administrators only.', max_digits=4, null=True, verbose_name='Consignment rate override'),
        ),
        migrations.RunPython(move_product_overrides_to_suppliers, migrations.RunPython.noop),
    ]
