# Generated by Django 5.2.17 on 2026-08-27 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='supplier_rate',
            field=models.DecimalField(choices=[(Decimal('0.50'), '50%'), (Decimal('0.30'), '30%')], decimal_places=2, help_text='Initially calculated from the product rule; it can be corrected manually.', max_digits=4),
        ),
    ]
