# Generated by Django 5.2.17 on 2026-08-27 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_rate_override',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.50'), 'Force 50%'), (Decimal('0.30'), 'Force 30%')], decimal_places=2, help_text='Leave blank for automatic campaign calculation.', max_digits=4, null=True, verbose_name='Supplier rate override'),
        ),
    ]
