# Generated by Django 5.2.17 on 2026-08-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_supplier_rate_override'),
        ('suppliers', '0002_supplier_consignment_rate_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_rate_override',
        ),
    ]
